[webservers]
webserver1 ansible_host=98.80.206.250 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/aws-monitoring-pipeline-key
webserver2 ansible_host=3.237.255.234 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/aws-monitoring-pipeline-key

[local]
localhost ansible_connection=local
