[webservers]
webserver1 ansible_host=98.92.149.198 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/aws-monitoring-pipeline-key
webserver2 ansible_host=100.54.142.69 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/aws-monitoring-pipeline-key

[local]
localhost ansible_connection=local
